[tool.poetry]
name = "mitidrivers"
version = "0.1.0"
description = "mitidrivers data generator"
authors = ["KhulnaSoft DevSec <security@khulnasoft.com>"]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
pandas = "^2.1.3"
Jinja2 = "^3.1.5"
stix2 = "^3.0.1"
colorama = ">=0.3.9"
future = ">=0.16.0"
requests = ">=2.31.0"
configparser = ">=3.5.0"
pymisp = ">=2.4.123"
flask = ">=1.0"
flask-caching = "^2.0.2"
cfscrape = "^2.1.1"
pyzipper = "^0.3.6"
dnspython = "^2.3.0"
ipy = "^1.1"
valhallaapi = "^0.6.0"
lief = "^0.15.0"
pefile = "^2023.2.7"
shortuuid = "^1.0.11"
plyara = "^2.1.1"
cryptography = "^42.0.4"
jsonschema = "^4.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
